language: go
dist: trusty

go:
  - 1.11.x

install:
  - go get -u golang.org/x/lint/golint

before_script:
  - golint pkg/agent/... pkg/drivers/... cmd/...
  - go tool vet */*.go
  - test -z $(gofmt -l pkg/agent/. pkg/drivers/. cmd/.)

script:
  - echo true

