---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: pod1
      image: docker.io/centos/tools:latest
      command:
        - /sbin/init
      volumeMounts:
        - mountPath: /etc/podinfo
          name: podinfo
          readOnly: false
        - mountPath: /var/lib/nimbess/cni/
          name: shared-dir
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
    - name: shared-dir
      hostPath:
        path: /var/lib/nimbess/cni/
